language: objective-c

osx_image: xcode9.3
xcode_project: ConfigCat.xcodeproj
xcode_scheme: ConfigCat
xcode_sdk:
- macosx10.13
- iphonesimulator11.3
- appletvsimulator11.3

after_success:
- bash <(curl -s https://codecov.io/bash)
