language: objective-c

osx_image: xcode9.3

stages:
  - test
  - coverage
  - pods

jobs:
  include:
  - stage: test
    script:
    - set -o pipefail
    - xcodebuild clean test -sdk iphonesimulator11.3 -project ConfigCat.xcodeproj -scheme "ConfigCat iOS" -destination "OS=11.3,name=iPhone 8" CODE_SIGNING_REQUIRED=NO
    - xcodebuild clean test -sdk appletvsimulator11.3 -project ConfigCat.xcodeproj -scheme "ConfigCat tvOS" -destination "OS=11.3,name=Apple TV 4K (at 1080p)" CODE_SIGNING_REQUIRED=NO
    - xcodebuild clean test -sdk macosx10.13 -project ConfigCat.xcodeproj -scheme "ConfigCat macOS" -destination "arch=x86_64"
  - stage: coverage
    script:
    - set -o pipefail
    - xcodebuild clean test -sdk macosx10.13 -project ConfigCat.xcodeproj -scheme "ConfigCat Coverage" -destination "arch=x86_64"
    - bash <(curl -s https://codecov.io/bash)
  - stage: pods
    script:
    - pod lib lint
