language: objective-c

osx_image: xcode9.3

env:
global:
- IOS_SCHEME="ConfigCat iOS"
- IOS_SDK=iphonesimulator11.3
- OSX_SCHEME="ConfigCat macOS"
- OSX_SDK=macosx10.13
- TVOS_SCHEME="ConfigCat tvOS"
- TVOS_SDK=appletvsimulator11.3

matrix:
- DESTINATION="OS=11.3,name=iPhone 8"        SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"
- DESTINATION="arch=x86_64"                  SCHEME="$OSX_SCHEME"     SDK="$OSX_SDK"
- DESTINATION="OS=11.3,name=Apple TV 1080p"  SCHEME="$TVOS_SCHEME"    SDK="$TVOS_SDK"

script:
  - set -o pipefail
  - xcodebuild clean test -sdk "$SDK" -configuration Release -project ConfigCat.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_REQUIRED=NO

after_success:
- bash <(curl -s https://codecov.io/bash)
